<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SanPhamSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now('Asia/Ho_Chi_Minh');

        $data = [
            [
                'ten' => 'Vitamin C 500mg',
                'mota' => 'Viên uống tăng sức đề kháng.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Nature Made',
                'mediaurl' => 'https://example.com/images/vitamin-c.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 120,
                'id_thuonghieu' => 1, // giả lập thương hiệu có id=1
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Sữa rửa mặt dịu nhẹ',
                'mota' => 'Phù hợp cho da nhạy cảm.',
                'xuatxu' => 'Hàn Quốc',
                'sanxuat' => 'Innisfree',
                'mediaurl' => 'https://example.com/images/suaruamat.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 90,
                'id_thuonghieu' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Máy đo huyết áp Omron',
                'mota' => 'Dụng cụ theo dõi sức khỏe tại nhà.',
                'xuatxu' => 'Nhật Bản',
                'sanxuat' => 'Omron',
                'mediaurl' => 'https://example.com/images/maydo-huyetap.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 250,
                'id_thuonghieu' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Nồi chiên không dầu 5L',
                'mota' => 'Nấu ăn nhanh chóng, ít dầu mỡ.',
                'xuatxu' => 'Trung Quốc',
                'sanxuat' => 'Philips',
                'mediaurl' => 'https://example.com/images/noichien.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 310,
                'id_thuonghieu' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Khẩu trang y tế 4 lớp',
                'mota' => 'Hộp 50 cái, chống bụi và vi khuẩn.',
                'xuatxu' => 'Việt Nam',
                'sanxuat' => 'VinMask',
                'mediaurl' => 'https://example.com/images/khau-trang.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 400,
                'id_thuonghieu' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Sữa tắm dưỡng ẩm Dove',
                'mota' => 'Dưỡng ẩm cho làn da mềm mịn.',
                'xuatxu' => 'Anh',
                'sanxuat' => 'Unilever',
                'mediaurl' => 'https://example.com/images/suatam-dove.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 180,
                'id_thuonghieu' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Sữa bột Abbott Grow',
                'mota' => 'Dành cho trẻ từ 2 tuổi trở lên.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Abbott',
                'mediaurl' => 'https://example.com/images/suabottre.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 500,
                'id_thuonghieu' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Áo sơ mi nam trắng',
                'mota' => 'Chất liệu cotton thoáng mát.',
                'xuatxu' => 'Việt Nam',
                'sanxuat' => 'Canifa',
                'mediaurl' => 'https://example.com/images/ao-somi.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 350,
                'id_thuonghieu' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Giày sneaker Adidas',
                'mota' => 'Phong cách thể thao, năng động.',
                'xuatxu' => 'Đức',
                'sanxuat' => 'Adidas',
                'mediaurl' => 'https://example.com/images/giay-adidas.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 600,
                'id_thuonghieu' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Bột giặt OMO Matic',
                'mota' => 'Giặt sạch vết bẩn, hương thơm lâu.',
                'xuatxu' => 'Việt Nam',
                'sanxuat' => 'Unilever',
                'mediaurl' => 'https://example.com/images/botgiat-omo.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 270,
                'id_thuonghieu' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ✅ thêm 10 sản phẩm nữa để đủ 20
            [
                'ten' => 'Laptop Dell Inspiron 15',
                'mota' => 'Máy tính xách tay cho công việc và học tập.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Dell',
                'mediaurl' => 'https://example.com/images/dell-inspiron.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 800,
                'id_thuonghieu' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Điện thoại iPhone 15 Pro',
                'mota' => 'Công nghệ mới nhất từ Apple.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Apple',
                'mediaurl' => 'https://example.com/images/iphone-15.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 2000,
                'id_thuonghieu' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Tai nghe AirPods Pro',
                'mota' => 'Chống ồn chủ động, pin lâu.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Apple',
                'mediaurl' => 'https://example.com/images/airpods.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 1500,
                'id_thuonghieu' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Tivi Samsung 55 inch 4K',
                'mota' => 'Màn hình sắc nét, giải trí đỉnh cao.',
                'xuatxu' => 'Hàn Quốc',
                'sanxuat' => 'Samsung',
                'mediaurl' => 'https://example.com/images/tivi-samsung.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 1200,
                'id_thuonghieu' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Máy giặt LG Inverter',
                'mota' => 'Tiết kiệm điện và nước.',
                'xuatxu' => 'Hàn Quốc',
                'sanxuat' => 'LG',
                'mediaurl' => 'https://example.com/images/maygiat-lg.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 950,
                'id_thuonghieu' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Quạt điều hòa Sunhouse',
                'mota' => 'Làm mát nhanh, tiết kiệm điện.',
                'xuatxu' => 'Việt Nam',
                'sanxuat' => 'Sunhouse',
                'mediaurl' => 'https://example.com/images/quat-sunhouse.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 410,
                'id_thuonghieu' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Bàn chải điện Oral-B',
                'mota' => 'Chăm sóc răng miệng hiện đại.',
                'xuatxu' => 'Đức',
                'sanxuat' => 'Oral-B',
                'mediaurl' => 'https://example.com/images/ban-chai.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 300,
                'id_thuonghieu' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Bánh quy Oreo',
                'mota' => 'Bánh ngọt nhân kem sữa.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Oreo',
                'mediaurl' => 'https://example.com/images/oreo.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 720,
                'id_thuonghieu' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Nước ngọt Coca-Cola',
                'mota' => 'Thức uống có gas, giải khát nhanh.',
                'xuatxu' => 'Mỹ',
                'sanxuat' => 'Coca-Cola',
                'mediaurl' => 'https://example.com/images/coca.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 2000,
                'id_thuonghieu' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Trà xanh Lipton',
                'mota' => 'Thức uống giải nhiệt, hương vị tự nhiên.',
                'xuatxu' => 'Anh',
                'sanxuat' => 'Lipton',
                'mediaurl' => 'https://example.com/images/lipton.jpg',
                'trangthai' => 'hoat_dong',
                'luotxem' => 650,
                'id_thuonghieu' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('san_pham')->insert($data);
    }
}
