<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ThongTinNguoiBanHangSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now('Asia/Ho_Chi_Minh');

        $shops = [
            [
                'id_nguoidung' => 21,
                'ten_cuahang' => 'Shop Sức Khỏe Xanh',
                'giayphep_kinhdoanh' => 'GP-1001',
                'theodoi' => 120,
                'luotban' => 50,
                'logo' => 'https://example.com/logos/shop1.png',
                'bianen' => 'https://example.com/banners/shop1.jpg',
                'mota' => 'Chuyên cung cấp vitamin và thực phẩm chức năng.',
                'diachi' => '123 Lê Lợi, Hà Nội',
                'sodienthoai' => '0901000001',
                'email' => 'shop1@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 22,
                'ten_cuahang' => 'Mỹ Phẩm Thiên Nhiên',
                'giayphep_kinhdoanh' => 'GP-1002',
                'theodoi' => 230,
                'luotban' => 120,
                'logo' => 'https://example.com/logos/shop2.png',
                'bianen' => 'https://example.com/banners/shop2.jpg',
                'mota' => 'Mỹ phẩm organic cho da nhạy cảm.',
                'diachi' => '45 Nguyễn Huệ, TP.HCM',
                'sodienthoai' => '0901000002',
                'email' => 'shop2@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 23,
                'ten_cuahang' => 'Thiết Bị Y Tế Omron',
                'giayphep_kinhdoanh' => 'GP-1003',
                'theodoi' => 500,
                'luotban' => 300,
                'logo' => 'https://example.com/logos/shop3.png',
                'bianen' => 'https://example.com/banners/shop3.jpg',
                'mota' => 'Máy đo huyết áp, máy xông khí dung chính hãng.',
                'diachi' => '89 Hai Bà Trưng, Đà Nẵng',
                'sodienthoai' => '0901000003',
                'email' => 'shop3@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 24,
                'ten_cuahang' => 'Gia Dụng Nhà Bếp',
                'giayphep_kinhdoanh' => 'GP-1004',
                'theodoi' => 320,
                'luotban' => 210,
                'logo' => 'https://example.com/logos/shop4.png',
                'bianen' => 'https://example.com/banners/shop4.jpg',
                'mota' => 'Nồi chiên, máy ép trái cây, bếp điện...',
                'diachi' => '77 Nguyễn Văn Cừ, Cần Thơ',
                'sodienthoai' => '0901000004',
                'email' => 'shop4@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 25,
                'ten_cuahang' => 'Khẩu Trang VinMask',
                'giayphep_kinhdoanh' => 'GP-1005',
                'theodoi' => 150,
                'luotban' => 90,
                'logo' => 'https://example.com/logos/shop5.png',
                'bianen' => 'https://example.com/banners/shop5.jpg',
                'mota' => 'Khẩu trang y tế 4 lớp chất lượng cao.',
                'diachi' => '12 Hoàng Hoa Thám, Hải Phòng',
                'sodienthoai' => '0901000005',
                'email' => 'shop5@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 26,
                'ten_cuahang' => 'Dove Care',
                'giayphep_kinhdoanh' => 'GP-1006',
                'theodoi' => 410,
                'luotban' => 300,
                'logo' => 'https://example.com/logos/shop6.png',
                'bianen' => 'https://example.com/banners/shop6.jpg',
                'mota' => 'Các sản phẩm chăm sóc da của Dove.',
                'diachi' => '59 Cách Mạng Tháng 8, TP.HCM',
                'sodienthoai' => '0901000006',
                'email' => 'shop6@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 27,
                'ten_cuahang' => 'Abbott Grow Store',
                'giayphep_kinhdoanh' => 'GP-1007',
                'theodoi' => 600,
                'luotban' => 450,
                'logo' => 'https://example.com/logos/shop7.png',
                'bianen' => 'https://example.com/banners/shop7.jpg',
                'mota' => 'Sữa bột và dinh dưỡng trẻ em.',
                'diachi' => '88 Điện Biên Phủ, Hà Nội',
                'sodienthoai' => '0901000007',
                'email' => 'shop7@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 28,
                'ten_cuahang' => 'Thời Trang Nam Canifa',
                'giayphep_kinhdoanh' => 'GP-1008',
                'theodoi' => 720,
                'luotban' => 310,
                'logo' => 'https://example.com/logos/shop8.png',
                'bianen' => 'https://example.com/banners/shop8.jpg',
                'mota' => 'Áo sơ mi, quần tây, vest nam.',
                'diachi' => '20 Bạch Mai, Hà Nội',
                'sodienthoai' => '0901000008',
                'email' => 'shop8@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 29,
                'ten_cuahang' => 'Adidas Official',
                'giayphep_kinhdoanh' => 'GP-1009',
                'theodoi' => 1200,
                'luotban' => 800,
                'logo' => 'https://example.com/logos/shop9.png',
                'bianen' => 'https://example.com/banners/shop9.jpg',
                'mota' => 'Giày sneaker, quần áo thể thao Adidas.',
                'diachi' => '101 Láng Hạ, Hà Nội',
                'sodienthoai' => '0901000009',
                'email' => 'shop9@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_nguoidung' => 30,
                'ten_cuahang' => 'OMO Matic Store',
                'giayphep_kinhdoanh' => 'GP-1010',
                'theodoi' => 650,
                'luotban' => 500,
                'logo' => 'https://example.com/logos/shop10.png',
                'bianen' => 'https://example.com/banners/shop10.jpg',
                'mota' => 'Bột giặt và sản phẩm giặt tẩy.',
                'diachi' => '45 Võ Văn Ngân, Thủ Đức',
                'sodienthoai' => '0901000010',
                'email' => 'shop10@example.com',
                'trangthai' => 'hoat_dong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('thongtin_nguoibanhang')->insert($shops);
    }
}
